export interface Diagnose {
  code: string;
  name: string;
}

export const F_DIAGNOSEN: Diagnose[] = [
  { code: "F32.0", name: "Leichte depressive Episode" },
  { code: "F32.1", name: "Mittelgradige depressive Episode" },
  { code: "F32.2", name: "Schwere depressive Episode ohne psychotische Symptome" },
  { code: "F32.8", name: "Sonstige depressive Episoden" },
  { code: "F32.9", name: "Depressive Episode, nicht näher bezeichnet" },
  { code: "F33.0", name: "Rezidivierende depressive Störung, gegenwärtig leichte Episode" },
  { code: "F33.1", name: "Rezidivierende depressive Störung, gegenwärtig mittelgradige Episode" },
  { code: "F33.2", name: "Rezidivierende depressive Störung, gegenwärtig schwere Episode ohne psychotische Symptome" },
  { code: "F33.4", name: "Rezidivierende depressive Störung, gegenwärtig remittiert" },
  { code: "F33.8", name: "Sonstige rezidivierende depressive Störungen" },
  { code: "F33.9", name: "Rezidivierende depressive Störung, nicht näher bezeichnet" },
  { code: "F34.1", name: "Dysthymia" },
  { code: "F40.00", name: "Agoraphobie ohne Panikstörung" },
  { code: "F40.01", name: "Agoraphobie mit Panikstörung" },
  { code: "F40.1", name: "Soziale Phobien" },
  { code: "F40.2", name: "Spezifische (isolierte) Phobien" },
  { code: "F41.0", name: "Panikstörung (episodisch paroxysmale Angst)" },
  { code: "F41.1", name: "Generalisierte Angststörung" },
  { code: "F41.2", name: "Angst und depressive Störung, gemischt" },
  { code: "F42.0", name: "Vorwiegend Zwangsgedanken oder Grübelzwang" },
  { code: "F42.1", name: "Vorwiegend Zwangshandlungen (Zwangsrituale)" },
  { code: "F42.2", name: "Zwangsgedanken und Zwangshandlungen, gemischt" },
  { code: "F43.0", name: "Akute Belastungsreaktion" },
  { code: "F43.1", name: "Posttraumatische Belastungsstörung" },
  { code: "F43.2", name: "Anpassungsstörungen" },
  { code: "F43.20", name: "Kurze depressive Reaktion" },
  { code: "F43.21", name: "Längere depressive Reaktion" },
  { code: "F43.22", name: "Angst und depressive Reaktion, gemischt" },
  { code: "F44.0", name: "Dissoziative Amnesie" },
  { code: "F45.0", name: "Somatisierungsstörung" },
  { code: "F45.2", name: "Hypochondrische Störung" },
  { code: "F45.3", name: "Somatoforme autonome Funktionsstörung" },
  { code: "F45.40", name: "Anhaltende somatoforme Schmerzstörung" },
  { code: "F45.41", name: "Chronische Schmerzstörung mit somatischen und psychischen Faktoren" },
  { code: "F48.0", name: "Neurasthenie" },
  { code: "F50.0", name: "Anorexia nervosa" },
  { code: "F50.2", name: "Bulimia nervosa" },
  { code: "F50.4", name: "Essattacken bei anderen psychischen Störungen (Binge-Eating)" },
  { code: "F51.0", name: "Nichtorganische Insomnie" },
  { code: "F51.1", name: "Nichtorganische Hypersomnie" },
  { code: "F60.0", name: "Paranoide Persönlichkeitsstörung" },
  { code: "F60.1", name: "Schizoide Persönlichkeitsstörung" },
  { code: "F60.2", name: "Dissoziale Persönlichkeitsstörung" },
  { code: "F60.30", name: "Emotional instabile Persönlichkeitsstörung: Impulsiver Typ" },
  { code: "F60.31", name: "Emotional instabile Persönlichkeitsstörung: Borderline-Typ" },
  { code: "F60.4", name: "Histrionische Persönlichkeitsstörung" },
  { code: "F60.5", name: "Anankastische (zwanghafte) Persönlichkeitsstörung" },
  { code: "F60.6", name: "Ängstliche (vermeidende) Persönlichkeitsstörung" },
  { code: "F60.7", name: "Abhängige (asthenische) Persönlichkeitsstörung" },
  { code: "F90.0", name: "Einfache Aktivitäts- und Aufmerksamkeitsstörung" },
  { code: "F90.1", name: "Hyperkinetische Störung des Sozialverhaltens" }
];
